//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatClienteMatriz_Afiliaciones
    {
        public int Id { get; set; }
        public int Id_Emp { get; set; }
        public int Id_Cd { get; set; }
        public int Id_Cte { get; set; }
        public int Id_Ter { get; set; }
        public string Convenio { get; set; }
        public Nullable<System.DateTime> Fecha_Alta { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> Id_DomicilioFiscal { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual CatDomicilioFiscal CatDomicilioFiscal { get; set; }
    }
}
