//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatClienteMatriz_Permisos
    {
        public int Id { get; set; }
        public Nullable<bool> DiasCredito { get; set; }
        public Nullable<bool> AcuerdoEcon { get; set; }
        public Nullable<bool> DatosFisc { get; set; }
        public Nullable<bool> AsigRIK { get; set; }
        public Nullable<bool> MOV80 { get; set; }
    
        public virtual CatCNac_Matriz CatCNac_Matriz { get; set; }
    }
}
