//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCNac_IntranetListaFranq
    {
        public int Id { get; set; }
        public Nullable<int> Id_Matriz { get; set; }
        public Nullable<int> FranqConsecionada { get; set; }
        public Nullable<int> ClienteMac { get; set; }
        public Nullable<int> UsuarioIntranet { get; set; }
        public Nullable<int> Moneda { get; set; }
        public Nullable<int> Productos { get; set; }
        public Nullable<int> SistemaPV { get; set; }
        public Nullable<int> DirFacturas { get; set; }
        public Nullable<int> ValorAgrCump { get; set; }
        public Nullable<int> id_Emp { get; set; }
    
        public virtual CatCNac_Matriz CatCNac_Matriz { get; set; }
        public virtual CatTMoneda CatTMoneda { get; set; }
        public virtual CatCNac_ProductosPermitidos CatCNac_ProductosPermitidos { get; set; }
        public virtual CatCNac_IntranetUsuarios CatCNac_IntranetUsuarios { get; set; }
    }
}
