//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCNac_IntranetUsuarios
    {
        public CatCNac_IntranetUsuarios()
        {
            this.CatCNac_IntranetListaFranq = new HashSet<CatCNac_IntranetListaFranq>();
        }
    
        public int Usu_IdUsuario { get; set; }
        public string Usu_Nombre { get; set; }
        public string Usu_ApPaterno { get; set; }
        public string Usu_ApMaterno { get; set; }
        public string Usu_Domicilio { get; set; }
        public string Usu_Colonia { get; set; }
        public string Usu_CodigoPostal { get; set; }
        public string Usu_Ciudad { get; set; }
        public Nullable<byte> Usu_IdEstado { get; set; }
        public string Usu_RegFed { get; set; }
        public string Usu_SegSocial { get; set; }
        public string Usu_LugarNac { get; set; }
        public string Usu_Nacionalidad { get; set; }
        public string Usu_Curp { get; set; }
        public string Usu_Email { get; set; }
        public string Usu_Usuario { get; set; }
        public string Usu_Clave { get; set; }
        public string Usu_ClaveNomina { get; set; }
        public Nullable<System.DateTime> Usu_FecAltaNomina { get; set; }
        public Nullable<int> Usu_NumUsuario { get; set; }
        public Nullable<int> Emp_IdEmpresa { get; set; }
        public Nullable<int> CenDi_Clave { get; set; }
        public Nullable<short> Dep_IdDepartamento { get; set; }
        public Nullable<bool> Usu_EstatusRegistro { get; set; }
        public Nullable<int> Pue_IdPuesto { get; set; }
        public string Usu_Telefono { get; set; }
        public string Usu_Fax { get; set; }
        public string Usu_Extension { get; set; }
        public string Usu_Messenger { get; set; }
        public string Usu_Skype { get; set; }
        public string Usu_Radio { get; set; }
        public string Usu_TelefonoMovil { get; set; }
        public string Usu_TelefonoPersonal { get; set; }
        public Nullable<System.DateTime> Usu_FecNac { get; set; }
        public Nullable<System.DateTime> Usu_FecReg { get; set; }
        public Nullable<System.DateTime> Usu_FecVigI { get; set; }
        public Nullable<System.DateTime> Usu_FecVigF { get; set; }
        public Nullable<int> Usu_Agente { get; set; }
        public Nullable<int> Usu_Agente1 { get; set; }
        public Nullable<int> Usu_JefeDirecto { get; set; }
        public Nullable<int> Usu_CteMacola { get; set; }
        public Nullable<int> Usu_AdminEd { get; set; }
        public Nullable<int> Usu_CteMacolaAntes { get; set; }
        public string Usu_RFCCDIK { get; set; }
        public Nullable<int> Usu_NoCDIK_Sian { get; set; }
        public Nullable<int> id_Emp { get; set; }
    
        public virtual ICollection<CatCNac_IntranetListaFranq> CatCNac_IntranetListaFranq { get; set; }
    }
}
