//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCNac_IntranetFran
    {
        public int Id { get; set; }
        public Nullable<int> TipoMoneda { get; set; }
        public Nullable<int> ProdPermitidos { get; set; }
        public Nullable<int> CatEspecial { get; set; }
        public Nullable<bool> Factura { get; set; }
        public Nullable<bool> FacturaExt { get; set; }
        public Nullable<bool> NotaCredito { get; set; }
        public Nullable<bool> NotaCargo { get; set; }
        public Nullable<bool> Cancelacion { get; set; }
        public Nullable<int> DiasCredito { get; set; }
        public Nullable<bool> CargaAcuse { get; set; }
        public Nullable<bool> Addenda { get; set; }
        public Nullable<bool> Descuentos { get; set; }
        public Nullable<double> PorcRequerido { get; set; }
        public Nullable<int> MetodoPago { get; set; }
        public string NumTarjeta { get; set; }
        public string Soportes { get; set; }
        public Nullable<int> AddendaTipo { get; set; }
        public Nullable<int> TipoNotaCred { get; set; }
    
        public virtual CatCNac_Matriz CatCNac_Matriz { get; set; }
    }
}
