//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatDomicilioFiscal
    {
        public CatDomicilioFiscal()
        {
            this.CatClienteMatriz_Afiliaciones = new HashSet<CatClienteMatriz_Afiliaciones>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_ClienteMatriz { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public string CP { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public string RFC { get; set; }
        public string Email_Fac { get; set; }
    
        public virtual ICollection<CatClienteMatriz_Afiliaciones> CatClienteMatriz_Afiliaciones { get; set; }
        public virtual CatCNac_Matriz CatCNac_Matriz { get; set; }
    }
}
