//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatProducto
    {
        public int Id_Emp { get; set; }
        public Nullable<int> Id_Cd { get; set; }
        public int Id_Prd { get; set; }
        public Nullable<int> Id_PrdLoc { get; set; }
        public Nullable<int> Id_Spo { get; set; }
        public int Id_Ptp { get; set; }
        public Nullable<int> Id_Cpr { get; set; }
        public Nullable<int> Id_Fam { get; set; }
        public Nullable<int> Id_Sub { get; set; }
        public Nullable<int> Id_Pvd { get; set; }
        public string Prd_Descripcion { get; set; }
        public string Prd_Presentacion { get; set; }
        public Nullable<int> Prd_AgrupadoSpo { get; set; }
        public Nullable<double> Prd_FactorConv { get; set; }
        public Nullable<bool> Prd_AparatoSisProp { get; set; }
        public Nullable<int> Prd_InvSeg { get; set; }
        public string Prd_UniNe { get; set; }
        public string Prd_UniNs { get; set; }
        public Nullable<int> Prd_Unico { get; set; }
        public Nullable<double> Prd_UniEmp { get; set; }
        public Nullable<bool> Prd_Colo { get; set; }
        public string Prd_Ren { get; set; }
        public Nullable<int> Prd_Mes { get; set; }
        public string Prd_Ubicacion { get; set; }
        public Nullable<double> Prd_Contribucion { get; set; }
        public Nullable<bool> Prd_Nuevo { get; set; }
        public Nullable<decimal> Prd_PesConTecnico { get; set; }
        public string Prd_CptSv { get; set; }
        public Nullable<bool> Prd_Activo { get; set; }
        public Nullable<System.DateTime> Prd_FecAlta { get; set; }
        public Nullable<double> Prd_PorUtilidades { get; set; }
        public string Prd_PlanAbasto { get; set; }
        public Nullable<int> Prd_Minimo { get; set; }
    }
}
