//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatTMoneda
    {
        public CatTMoneda()
        {
            this.CatCNac_IntranetListaFranq = new HashSet<CatCNac_IntranetListaFranq>();
        }
    
        public int Id_Emp { get; set; }
        public int Id_Mon { get; set; }
        public string Mon_Descripcion { get; set; }
        public string Mon_Abrev { get; set; }
        public double Mon_TipCambio { get; set; }
        public Nullable<bool> Mon_Activo { get; set; }
        public int Id_Cd { get; set; }
    
        public virtual ICollection<CatCNac_IntranetListaFranq> CatCNac_IntranetListaFranq { get; set; }
    }
}
