//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatUsuario
    {
        public int Id_Emp { get; set; }
        public int Id_Cd { get; set; }
        public int Id_U { get; set; }
        public string U_Nombre { get; set; }
        public string U_NombreCorto { get; set; }
        public string U_Correo { get; set; }
        public Nullable<System.DateTime> U_FNac { get; set; }
        public string U_NumNomina { get; set; }
        public Nullable<bool> U_Activo { get; set; }
        public Nullable<int> id_id_U { get; set; }
        public Nullable<int> Id_Tu { get; set; }
        public Nullable<bool> U_VerTodo { get; set; }
        public Nullable<bool> U_MultiOfi { get; set; }
        public Nullable<int> Id_Rik { get; set; }
        public Nullable<bool> U_SusCredito { get; set; }
        public Nullable<int> U_DiasVencimiento { get; set; }
        public Nullable<bool> U_AutorizaPrecio { get; set; }
    }
}
