//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Data.Entity.Core.Objects;
    
    public partial class SIANCENTRAL_CCEntities1 : DbContext
    {
        public SIANCENTRAL_CCEntities1()
            : base("name=SIANCENTRAL_CCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CatACYS_Cliente> CatACYS_Cliente { get; set; }
        public DbSet<CatACYS_CondPago> CatACYS_CondPago { get; set; }
        public DbSet<CatACYS_DirFiscales> CatACYS_DirFiscales { get; set; }
        public DbSet<CatACYS_OtrosApoyos> CatACYS_OtrosApoyos { get; set; }
        public DbSet<CatAcys_Productos> CatAcys_Productos { get; set; }
        public DbSet<CatACYS_RecPedido> CatACYS_RecPedido { get; set; }
        public DbSet<CatACYS_ServValor> CatACYS_ServValor { get; set; }
        public DbSet<CatACYS_SIANCENTRAL> CatACYS_SIANCENTRAL { get; set; }
        public DbSet<CatDomicilioFiscal> CatDomicilioFiscal { get; set; }
        public DbSet<CatProducto> CatProducto { get; set; }
        public DbSet<CatClienteMatriz_Afiliaciones> CatClienteMatriz_Afiliaciones { get; set; }
        public DbSet<CatClienteMatriz_Permisos> CatClienteMatriz_Permisos { get; set; }
        public DbSet<CatTMoneda> CatTMoneda { get; set; }
        public DbSet<CatCNac_Addenda> CatCNac_Addenda { get; set; }
        public DbSet<CatCNac_CatalogoEspecial> CatCNac_CatalogoEspecial { get; set; }
        public DbSet<CatCNac_MetPago> CatCNac_MetPago { get; set; }
        public DbSet<CatCNac_ProductosPermitidos> CatCNac_ProductosPermitidos { get; set; }
        public DbSet<CatCNac_TipoNotaCred> CatCNac_TipoNotaCred { get; set; }
        public DbSet<CatCNac_Soportes> CatCNac_Soportes { get; set; }
        public DbSet<CatCNac_IntranetFran> CatCNac_IntranetFran { get; set; }
        public DbSet<CatCNac_IntranetListaFranq> CatCNac_IntranetListaFranq { get; set; }
        public DbSet<CatCNac_SistemasPV> CatCNac_SistemasPV { get; set; }
        public DbSet<CatCNac_ACYS> CatCNac_ACYS { get; set; }
        public DbSet<CatCNac_TipoCuenta> CatCNac_TipoCuenta { get; set; }
        public DbSet<CatCNac_PermisosCamposACYS> CatCNac_PermisosCamposACYS { get; set; }
        public DbSet<CatCNac_Matriz> CatCNac_Matriz { get; set; }
        public DbSet<CatACYS_Productos_DatosGar> CatACYS_Productos_DatosGar { get; set; }
        public DbSet<CatACYS_Productos_DatosGar_Fechas> CatACYS_Productos_DatosGar_Fechas { get; set; }
        public DbSet<CatCNac_Condiciones> CatCNac_Condiciones { get; set; }
        public DbSet<CatCDI> CatCDI { get; set; }
        public DbSet<CatUsuario> CatUsuario { get; set; }
        public DbSet<CatCNac_Estructura> CatCNac_Estructura { get; set; }
        public DbSet<CatCNac_Usuario> CatCNac_Usuario { get; set; }
        public DbSet<CatCNac_RolAuditorias> CatCNac_RolAuditorias { get; set; }
        public DbSet<CatCNac_RolECommerce> CatCNac_RolECommerce { get; set; }
        public DbSet<CatCNac_UsuarioPermisos> CatCNac_UsuarioPermisos { get; set; }
        public DbSet<CatCNac_EstatusSolicitudes> CatCNac_EstatusSolicitudes { get; set; }
        public DbSet<CatCNac_Solicitudes> CatCNac_Solicitudes { get; set; }
        public DbSet<CatCNac_Solicitudes_DirFiscal> CatCNac_Solicitudes_DirFiscal { get; set; }
        public DbSet<CatCNac_RemisionesMov80> CatCNac_RemisionesMov80 { get; set; }
        public DbSet<CatCNac_IntranetUsuarios> CatCNac_IntranetUsuarios { get; set; }
    
        public virtual ObjectResult<spCC_ConsultarAfiliaciones_Result> spCC_ConsultarAfiliaciones(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCC_ConsultarAfiliaciones_Result>("spCC_ConsultarAfiliaciones", idParameter);
        }
    
        public virtual ObjectResult<spComboNiveles_Result> spComboNiveles(Nullable<int> id_Matriz)
        {
            var id_MatrizParameter = id_Matriz.HasValue ?
                new ObjectParameter("Id_Matriz", id_Matriz) :
                new ObjectParameter("Id_Matriz", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spComboNiveles_Result>("spComboNiveles", id_MatrizParameter);
        }
    
        public virtual ObjectResult<spCNacDireccionesFiscalesACYS_Result> spCNacDireccionesFiscalesACYS(Nullable<int> id_ACYS)
        {
            var id_ACYSParameter = id_ACYS.HasValue ?
                new ObjectParameter("Id_ACYS", id_ACYS) :
                new ObjectParameter("Id_ACYS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCNacDireccionesFiscalesACYS_Result>("spCNacDireccionesFiscalesACYS", id_ACYSParameter);
        }
    
        public virtual int spCatCN_DuplicarACYS(Nullable<int> id_AcysADuplicar)
        {
            var id_AcysADuplicarParameter = id_AcysADuplicar.HasValue ?
                new ObjectParameter("Id_AcysADuplicar", id_AcysADuplicar) :
                new ObjectParameter("Id_AcysADuplicar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCatCN_DuplicarACYS", id_AcysADuplicarParameter);
        }
    }
}
